//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _02.DaysOfWeek.Client.DayOfWeekService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DayOfWeekService.IDaysOfWeekService")]
    public interface IDaysOfWeekService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDaysOfWeekService/GetData", ReplyAction="http://tempuri.org/IDaysOfWeekService/GetDataResponse")]
        string GetData(System.DateTime dateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDaysOfWeekService/GetData", ReplyAction="http://tempuri.org/IDaysOfWeekService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(System.DateTime dateTime);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDaysOfWeekServiceChannel : _02.DaysOfWeek.Client.DayOfWeekService.IDaysOfWeekService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DaysOfWeekServiceClient : System.ServiceModel.ClientBase<_02.DaysOfWeek.Client.DayOfWeekService.IDaysOfWeekService>, _02.DaysOfWeek.Client.DayOfWeekService.IDaysOfWeekService {
        
        public DaysOfWeekServiceClient() {
        }
        
        public DaysOfWeekServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DaysOfWeekServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DaysOfWeekServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DaysOfWeekServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(System.DateTime dateTime) {
            return base.Channel.GetData(dateTime);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(System.DateTime dateTime) {
            return base.Channel.GetDataAsync(dateTime);
        }
    }
}
