-- MySQL Script generated by MySQL Workbench
-- 10/09/15 20:50:11
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Faculties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Faculties` (
  `id` INT NOT NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departments` (
  `id` INT NOT NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `Faculties_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `Faculties_id`)  COMMENT '',
  INDEX `fk_Departments_Faculties1_idx` (`Faculties_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Departments_Faculties1`
    FOREIGN KEY (`Faculties_id`)
    REFERENCES `mydb`.`Faculties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professors` (
  `id` INT NOT NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `Departments_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `Departments_id`)  COMMENT '',
  INDEX `fk_Professors_Departments1_idx` (`Departments_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Professors_Departments1`
    FOREIGN KEY (`Departments_id`)
    REFERENCES `mydb`.`Departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Courses` (
  `id` INT NOT NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `Professors_id` INT NOT NULL COMMENT '',
  `Departments_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `Professors_id`, `Departments_id`)  COMMENT '',
  INDEX `fk_Courses_Professors1_idx` (`Professors_id` ASC)  COMMENT '',
  INDEX `fk_Courses_Departments1_idx` (`Departments_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Courses_Professors1`
    FOREIGN KEY (`Professors_id`)
    REFERENCES `mydb`.`Professors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Courses_Departments1`
    FOREIGN KEY (`Departments_id`)
    REFERENCES `mydb`.`Departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Students` (
  `id` INT NOT NULL COMMENT '',
  `first_name` VARCHAR(45) NULL COMMENT '',
  `last_name` VARCHAR(45) NULL COMMENT '',
  `Faculties_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `Faculties_id`)  COMMENT '',
  INDEX `fk_Students_Faculties1_idx` (`Faculties_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Students_Faculties1`
    FOREIGN KEY (`Faculties_id`)
    REFERENCES `mydb`.`Faculties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StudentCourses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`StudentCourses` (
  `Students_id` INT NOT NULL COMMENT '',
  `Courses_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Students_id`, `Courses_id`)  COMMENT '',
  INDEX `fk_StudentCourses_Courses1_idx` (`Courses_id` ASC)  COMMENT '',
  CONSTRAINT `fk_StudentCourses_Students`
    FOREIGN KEY (`Students_id`)
    REFERENCES `mydb`.`Students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StudentCourses_Courses1`
    FOREIGN KEY (`Courses_id`)
    REFERENCES `mydb`.`Courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Titles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Titles` (
  `id` INT NOT NULL COMMENT '',
  `type` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProfessorsTitles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProfessorsTitles` (
  `Professors_id` INT NOT NULL COMMENT '',
  `Titles_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Professors_id`, `Titles_id`)  COMMENT '',
  INDEX `fk_ProfessorsTitles_Titles1_idx` (`Titles_id` ASC)  COMMENT '',
  CONSTRAINT `fk_ProfessorsTitles_Professors1`
    FOREIGN KEY (`Professors_id`)
    REFERENCES `mydb`.`Professors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProfessorsTitles_Titles1`
    FOREIGN KEY (`Titles_id`)
    REFERENCES `mydb`.`Titles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
